version: "3.7"
services:
  frontend:
    image: aminealami7/frontend
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: frontend
    restart: always
  server:
    container_name: server
    restart: always
    image: aminealami7/server
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
