name: Docker Compose CI



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-cli@v1
      with:
        compose-file: docker-compose.yml

    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
