name: Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runs-on: ubuntu-20.04

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Install Backend Dependencies
      run: |
        npm install

    - name: Run Backend Tests
      run: |
        npm test

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t aminealami7/server ./server
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push aminealami7/server